export { default as acl      } from './methods/acl';
export { default as copy     } from './methods/copy';
export { default as delete   } from './methods/delete';
export { default as get      } from './methods/get';
export { default as head     } from './methods/head';
export { default as mkcol    } from './methods/mkcol';
export { default as move     } from './methods/move';
export { default as options  } from './methods/options';
export { default as post     } from './methods/post';
export { default as propfind } from './methods/propfind';
export { default as proppatch} from './methods/proppatch';
export { default as lock     } from './methods/lock';
export { default as put      } from './methods/put';
export { default as patch    } from './methods/patch';
export { default as report   } from './methods/report';
export { default as search   } from './methods/search';
export { default as unlock   } from './methods/unlock';